# This is a basic workflow to help you get started with Actions

name: release

# Controls when the action will run.
on:
  push:
    tags:
      - 'v*.*.*'
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ feature/restructure ]
  #pull_request:
  #  branches: [ feature/restructure ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    container: viur/viur-flare-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}

      - name: fetch changelog info
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}